### ISSUE TITLE
Vite warning

### ISSUE THREAD

**Issue by Taha-Firoz** [metonym/svelte-pincode#12]
Vite gives this warning when I run my project.

Here are my deps
```
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"typescript": "^4.7.4",
		"vite": "^3.0.0",
```

```svelte-pincode doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix```

**Comment by metonym** [comment]
Thanks for reporting – fixed in [v2.1.2](https://github.com/metonym/svelte-pincode/releases/tag/v2.1.2).
